services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
  mariadb:
    image: mariadb:11
    environment:
      MARIADB_ROOT_PASSWORD: mariadb
      MARIADB_DATABASE: mariadb
    ports:
      - "3306:3306"
    command:
      # Habilita LOAD DATA LOCAL INFILE no servidor
      - --local-infile=1
